# figaro heroku:set -e production

stripeTestPublish: "pk_test_51HGYikHvKdEDURjLgT8xONPGMsHFuSzSjnBdPmkhDIWTvPaJPemADUh5b1o3zyo6rjLRBOVRD5dIgPFYlajQ05zy00yRYPDNxL"
stripeTestSecret:   "sk_test_51HGYikHvKdEDURjLGVLr6d5f4ieW5zEeI56EDTCdEZKUeNMsKx2aaRuuoq3yIDPgvs7AaIPkX0fN9ivswODa7MNB00YnqPL113"
stripeLivePublish: "pk_test_51HGYikHvKdEDURjLgT8xONPGMsHFuSzSjnBdPmkhDIWTvPaJPemADUh5b1o3zyo6rjLRBOVRD5dIgPFYlajQ05zy00yRYPDNxL"
stripeLiveSecret:   "sk_test_51HGYikHvKdEDURjLGVLr6d5f4ieW5zEeI56EDTCdEZKUeNMsKx2aaRuuoq3yIDPgvs7AaIPkX0fN9ivswODa7MNB00YnqPL113"